export const textbookMockData = [
  {
    id: "mock-1",
    date: "02/01/2026",
    state: "Telangana",
    board: "SSC",
    classId: "10",
    className: "10th",
    subjectId: "telugu",
    subjectName: "Telugu",
    bookName: "Telugu Reader",
    publisher: "SCERT Telangana",
    edition: "2025-26",
    description: "Telangana State Telugu textbook",
    textbookUrl: "",
    pdfUrl: "",
  },
  {
    id: "mock-2",
    date: "02/01/2026",
    state: "Karnataka",
    board: "SSC",
    classId: "10",
    className: "10th",
    subjectId: "physics",
    subjectName: "Physics",
    bookName: "Physics Textbook",
    publisher: "State Education Board",
    edition: "2025-26",
    description: "Secondary school Physics textbook",
    textbookUrl: "",
    pdfUrl: "",
  },
  {
    id: "mock-3",
    date: "02/01/2026",
    state: "Karnataka",
    board: "CBSE",
    classId: "12",
    className: "12th",
    subjectId: "social",
    subjectName: "Social",
    bookName: "Social Science",
    publisher: "CBSE Publications",
    edition: "2025-26",
    description: "CBSE Social Science textbook",
    textbookUrl: "",
    pdfUrl: "",
  },
  {
    id: "mock-4",
    date: "02/01/2026",
    state: "Telangana",
    board: "CBSE",
    classId: "12",
    className: "12th",
    subjectId: "english",
    subjectName: "English",
    bookName: "English Core",
    publisher: "NCERT",
    edition: "2025-26",
    description: "CBSE English course textbook",
    textbookUrl: "",
    pdfUrl: "",
  },
];
